### ISSUE TITLE
Add .env to define ENS deployment addresses

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fdp-create-account#1]

**Comment by molekilla** [comment]
the issue I see here is that fdp-storage/fdp-contracts  requires a CI to build the javascript library which contains the deployed addresses.

 This is good, but we need to (as this ticket says) externally defined addresses in case we want to connect to other environment than mainnet/testnet defined by CI. Overall everything seems like I will use it in the app

**Comment by molekilla** [comment]
pls also add testnet addresses and which network, in  this case gorli

**Comment by molekilla** [comment]
@tomicvladan @IgorShadurin This is how to fix the environment, we need to understand though how to automate it

- All the steps related to fdp-play, the last command similar to this `fdp-play start --detach --blockchain-image fairdatasociety/fdp-contracts-blockchain:1.2.0 1.6.1`
- Then go to fdp-contracts and redeploy `npm run deploy:bee`
- Copy and paste those address into the REACT_* environments variables

Once you register, you should get this screen

![Screenshot from 2022-07-08 13-54-35](https://user-images.githubusercontent.com/1248071/178053585-b3dba757-e49a-4a07-948e-7eaff9f3ed04.png)

**Comment by tfius** [comment]
this should go to readme

**Comment by crtahlin** [comment]
Viktor: let's use fdp-contract hardcoded values. 

@tomicvladan check current state and close if not relevant.
