### ISSUE TITLE
add chain information

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fdp-create-account#10]
https://github.com/fairDataSociety/fdp-create-account/blob/0469927e8bfbab9ddd0e5335892ad6334b7d9825/src/pages/register/register.tsx#L230

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-create-account/10?planning-poker) with ZenHub @tomicvladan @tfius @nugaon
