### ISSUE TITLE
Address of an account is not specified during account creation

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-create-account#142]
1) Open "https://create.staging.fairdatasociety.org/#/register"
2) Enter username and password
3) Click Register
4) Click New address
5) Pass the mnemonic verification dialog
6) You will see the text below without an address which should be topped up

Expected: address of the account should be displayed.

<img width="1720" alt="Screenshot 2022-12-01 at 10 52 08" src="https://user-images.githubusercontent.com/1595061/204998310-7806a6dd-c760-4b76-b56a-d0b64ac35043.png">

**Comment by tfius** [comment]
who changed this, before address was displayed ?

**Comment by IgorShadurin** [comment]
I'm not sure how it was before, but it's not clear to me how to top up the wallet by following these instructions

**Comment by tomicvladan** [comment]
@IgorShadurin Do you have any console error?

**Comment by IgorShadurin** [comment]
> @IgorShadurin Do you have any console error?

nope
