### ISSUE TITLE
Error when registering user account - when testing locally on fdp-play

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fdp-create-account#149]
Error: call revert exception
![image](https://user-images.githubusercontent.com/520570/206903184-968681f1-aaa5-48fe-9201-12f939008f71.png)

info about updating .env variables after starting `fdp-play` needs to be mentioned somewhere before this step:

https://github.com/fairDataSociety/fdp-create-account/blob/4077d0b0e302558f1b8433ecb37d05884ff4beea/README.md?plain=1#L56

**Comment by tomicvladan** [comment]
Hi @rampall , all environment variables are listed in the `Configuration` section: https://github.com/fairDataSociety/fdp-create-account/blob/4077d0b0e302558f1b8433ecb37d05884ff4beea/README.md?plain=1#L5-L22

If you are using fdp-play, you don't have to specify contract addresses. You can just set `REACT_APP_ENVIRONMENT=LOCALHOST` and all fdp-play addresses will be used by default.

**Comment by rampall** [comment]
ah, yes i see! it works!
