### ISSUE TITLE
Add info which chain should be used for transaction and extra info

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fdp-create-account#18]
Commenting on screenshot:
![image](https://user-images.githubusercontent.com/1554520/185361937-209d0c48-b67a-49f6-b0f0-8179f8d5834c.png)

There should be more info here:
- which chain to use 
- the minimum amount of funds
- the maximum amount of funds
- disclaimer that the funds might be lost / cannot be recovered? how can they be recovered?

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-create-account/18?planning-poker) with ZenHub @tomicvladan @tfius @nugaon

**Comment by tomicvladan** [comment]
@crtahlin In the latest version there is information about chain. But for the maximum and minimum amount, that cannot be calculated. And regarding disclaimer, could you provide me an appropriate sentence for that?

**Comment by crtahlin** [comment]
"Disclaimer: Account integrity persistence and security are not assured. Expect that funds used for account might be lost, as well as any data the account uses."
