### ISSUE TITLE
Fix mixing resources issue

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fdp-create-account#19]
See screenshot:
![image](https://user-images.githubusercontent.com/1554520/185636241-a8c9644b-02c6-4c5a-91bd-5d9448c60b8e.png)

Possibly the registration fails due to requesting http & https via same page (?).

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-create-account/19?planning-poker) with ZenHub @tomicvladan @tfius @nugaon

**Comment by tomicvladan** [comment]
I think this PR will fix it https://github.com/fairDataSociety/fdp-create-account/pull/20. But we must deploy it first to find out.

**Comment by crtahlin** [comment]
@tomicvladan has this been fixed, can it be closed?

**Comment by tomicvladan** [comment]
It's no more relevant.
