### ISSUE TITLE
Change default min balance for Sepolia

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-create-account#251]
1 - At the moment, when registering through Sepolia, a minimum balance of 0.004 ETH is required. This is almost 10 times more than what is needed at the moment. I propose to reduce the minimum balance to 0.001, so that there is enough for registration and there will be a reserve in case of an increase in costs.

* Registration https://sepolia.etherscan.io/tx/0x6afb722a63432fd775c208269d3436ee9fd8648f704bcf1624dec7a2f651d1b8 - 0.000198 SepoliaETH
* Set resolver https://sepolia.etherscan.io/tx/0x7cc06d5d269cafc14603df4757d71b6ede5644ca333d059db14ac13cc43d83db - 0.00007323 SepoliaETH
* Set pubkey https://sepolia.etherscan.io/tx/0x331e20de45aa71b6094fc7669854421974e42626ba597c635cd621651d9f6ab6 - 0.00011723 SepoliaETH
* Total ~0.00038846 SepoliaETH

<img width="1180" alt="Screenshot 2023-06-01 at 13 30 45" src="https://github.com/fairDataSociety/fdp-create-account/assets/1595061/a7d80350-b452-4345-a4d9-c62f9fe58f1b">

**Comment by tomicvladan** [comment]
Min balance is calculated by querying RPC for gas amount and Alchemy for current gas price. And then the value is doubled because the calculation is unreliable.
If calculation can't get lesser amount then needed, maybe we could just remove multiplication by 2?

**Comment by IgorShadurin** [comment]
> Min balance is calculated by querying RPC for gas amount and Alchemy for current gas price. And then the value is doubled because the calculation is unreliable. If calculation can't get lesser amount then needed, maybe we could just remove multiplication by 2?

Is 0.004 calculated based on Alchemy? Can you point me to the place in the code where this amount is calculated?

**Comment by tomicvladan** [comment]
Sure, this is the function:
https://github.com/fairDataSociety/fdp-create-account/blob/d0d9d80cf7b7f19ed20d07dde6522bc882ab1044/src/context/account.context.tsx#L107-L131

**Comment by tomicvladan** [comment]
Actually, now when I checked the code. Seems that the 0.004 is default value and estimation didn't work. The default value set for Sepolia is 0.002, so we can change that value.
https://github.com/fairDataSociety/fdp-create-account/blob/d0d9d80cf7b7f19ed20d07dde6522bc882ab1044/src/context/network.context.tsx#L10-L24

**Comment by IgorShadurin** [comment]
> Actually, now when I checked the code. Seems that the 0.004 is default value and estimation didn't work. The default value set for Sepolia is 0.002, so we can change that value.
> 
> https://github.com/fairDataSociety/fdp-create-account/blob/d0d9d80cf7b7f19ed20d07dde6522bc882ab1044/src/context/network.context.tsx#L10-L24

Great. Let's change it.

**Comment by IgorShadurin** [comment]
You set a minimum balance of 0.001 ETH, and then in the UI it is multiplied by 2 and the user is required to deposit 0.002 ETH. Although 0.001 ETH is already an amount with a margin. Therefore, you need to change the minimum amount to 0.0005 so that 0.001 ETH is displayed in the UI. Right?
