### ISSUE TITLE
Too many request to xdai gateway when waiting for account funding 

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fdp-create-account#29]
right now there are multiple calls to xdai.gateway
it should be every 10s not more

**Comment by tomicvladan** [comment]
Payment is checked on every 10 seconds:

https://github.com/fairDataSociety/fdp-create-account/blob/881db54a1dca05bcd3332d0a0e374f3581bd808b/src/pages/register/waiting-payment.tsx#L51-L55

But it seems that ethers.js triggers two http requests for checking payment.

**Comment by tfius** [comment]
maybe to 15s ?
