### ISSUE TITLE
Add Footer 

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fdp-create-account#35]
First column:
**ABOUT**
FDS logo (link to fairdatasociety.org)
SWARM logo (link to eth swarm org) 
app version + (mainnet|testnet) (link to github)

Second column
**COMMUNITY**
Ecosystem (portal.fairdatasociety.org) 
Twitter  (@FairDataSociety)
Discord  (https://discord.com/channels/888359049551310869/940628803250704394)

Third column: 
**RESOURCES**
Documentation
Github
Blog

Fourth Column
**EXTENSIONS**
Blossom (Add links on store)
Swarm (Add links to store)

**Comment by tomicvladan** [comment]
PR: https://github.com/fairDataSociety/fdp-create-account/pull/45
