### ISSUE TITLE
Comments on Migrate Account screen

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fdp-create-account#38]
See screenshot:

![image](https://user-images.githubusercontent.com/1554520/188623942-bde92494-46ed-4fae-934d-231d9dff3022.png)

- "... new features" should be a link pointing to a document or site (release notes?) that lists the new features. 
- there should also be a sentence explaining what will happen with the migration. e.g.: "Migration will move data from your FairOS version XXX account to version ZZZ account. You should stop using your old account as the data on it will AAAAAA"
- "Password" field should specify whether that is an old or a new password that is supposed to be entered?
- "completely" ---> "a completely"

NOTE: Could not try out actual migration, as I don't seem to have an old testnet account.

**Comment by tomicvladan** [comment]
@crtahlin Could you be more specific regarding the second change? How exactly the sentence should look like?

And regarding the password. That's actually both new and old password. I'm not sure what label would be appropriate.

**Comment by crtahlin** [comment]
I actually do not know about the second change, which versions should be referenced etc., I hope @tfius can help out here. 

As far as password goes, should we not use this chance to allow for specifying a new / different / stronger password for the new storage if we allow change of username? At mininum, if same password is used for both - move the password field above the checkbox and rename checkbox label to "Migrate using the same username and password". But it would really make sense to also offer change of password.

**Comment by tomicvladan** [comment]
There is no option to change password in fairOS, at least it's not mentioned in the documentation:

**Comment by crtahlin** [comment]
Then I guess it does not make sense to change the username either, @tfius ?

**Comment by tomicvladan** [comment]
Is this issue still relevant? @tfius @crtahlin
