### ISSUE TITLE
Restore from mnemomic fails

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fdp-create-account#41]
See animated GIF:

![Restore-from-mnemonic-errors](https://user-images.githubusercontent.com/1554520/188629566-d8343601-11d2-4ac9-9cc7-29f598cb47da.gif)

Not 100% sure that mnemonic is valid. Still, if not, it should say that it is not. And "Try again" button should allow for another "try".

**Comment by tfius** [comment]
where did you copy text from ?
i copied from notepad, notepad++ and vs code and it works, even if new lines, but does not work if numerals are included (ie 1., 2. ... etc)

**Comment by crtahlin** [comment]
Logseq; I copied on previous occasions and it worked. It might be corrupt, not 100% sure. But in any case, the "Try again" button should work.

**Comment by tomicvladan** [comment]
It seems the error is not related to mnemonic. The error is thrown from the `extractMessageFromFailedTx` function which is from `fdp-contracts`. That means that the gateway returned a response that's not JSON and cannot be parsed.

**Comment by tomicvladan** [comment]
The try again button tries to make a new transaction if previous one failed. There is no sense to get back to the mnemonic page if it was correct.

**Comment by crtahlin** [comment]
Makes sense, but from the user perspective, there is an error about the mnemonic, yet the user cannot try enter another one. I have no good suggestion how to make the process better though. If @tfius does not have a suggestion, close the issue.

**Comment by tomicvladan** [comment]
If mnemonic is wrong, then the app won't let the user submit the form. But we could change the behavior of the try again button to show the form again?

**Comment by tomicvladan** [comment]
Not relevant anymore.
