### ISSUE TITLE
Funding the account flow

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fdp-create-account#42]
After checking the mnemonic, the screen for the funding is shown.

- It does not say how much funds need to be sent. It should say sth like "Suggested amounts for Goerli testnet are 0.1 gEth and 1 gBZZ."
(If that makes sense; registration went through using those.)
- The address to send to disappears after a while (or exactly when gEth arrive?), but it is still needed for sending gBZZ. Instead of dissapperaing, the screen should say sth like "Current state of account: X gEth ; Y gBZZ" where X and Y are the amounts detected on the account.

After successful registration the following screen is shown:

![image](https://user-images.githubusercontent.com/1554520/188632024-c6e3a2c0-d487-4a35-bd98-6bda53ed8514.png)

- the Balance field should show two pieces of information: the amount of gEth and amount of gBZZ. The number of decimal places should be taken into account for each currency, so that human readable numbers are shown. 
- there should also be additional information available on how to use your account (adding https://github.com/fairDataSociety/fdp-create-account/issues/35 will help), specifically add at the bottom:
"You can use your account to login into [Fairdrive][link to fairdrive on testnet] and other dApps!"
(Note that on mainnet, the link should be to mainnet Fairdrive - so this should be configurable dependent on deployment!)

**Comment by tfius** [comment]
one does not need the gbzz at this stage, but yes will be needed in the future.

**Comment by crtahlin** [comment]
I assumed gbzz was needed; I guess it was coincidence that the account creating went through just at the time when the gBZZ arrived.
