### ISSUE TITLE
bug: duplicate words conflict with mnemonic UI

### ISSUE THREAD

**Issue by molekilla** [fairDataSociety/fdp-create-account#44]
The React list needs to use a sequential key, not the word name

![Screenshot from 2022-09-05 07-44-57](https://user-images.githubusercontent.com/1248071/188642372-63a7acf9-a247-4551-b53f-fbc565011c08.png)

**Comment by tomicvladan** [comment]
Where exactly is words used as keys?

**Comment by crtahlin** [comment]
@tomicvladan sent via DM
