### ISSUE TITLE
display error message from EVM

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fdp-create-account#5]
when transaction fails or there is error display error from RPC message and not "Cannot check username. Network currently unavailable" 
for example error message from RPC was: 'VM Exception while processing transaction: revert'

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-create-account/5?planning-poker) with ZenHub @tomicvladan @tfius @nugaon

**Comment by tomicvladan** [comment]
Fixed.
