### ISSUE TITLE
fix after funds are transfered and error is 'Error: Postage batch not exists' 

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fdp-create-account#7]
1. display error to the user 
2. 'press try' again returns user to new account creation (effectively loosing transferred funds 
3. should go to and try to create SOCs again not new account creation in this case (postage batch not exits)
![image](https://user-images.githubusercontent.com/1674145/183629029-2df8d608-731a-4b4f-bbee-28f959d5a70f.png)

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-create-account/7?planning-poker) with ZenHub @tomicvladan @tfius @nugaon
