### ISSUE TITLE
[BLOCKER] Error creating FDS account after funding it

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fdp-create-account#91]
In both Firefox and Chrome, error occurs after funding is sent to account. See screenshots:

![image](https://user-images.githubusercontent.com/1554520/193211146-8adbd6c9-a78f-4de9-924e-a9ebb5d2cf6a.png)

![image](https://user-images.githubusercontent.com/1554520/193211218-53c1d423-7a86-4ac4-8f47-f32fca0ba2a7.png)

**Comment by tomicvladan** [comment]
not relevant anymore
